# -*- Mode: Eagle -*-
#
# Sample drill rack file.
#
# drill_size is the size of the drill bit.
# minimum is the smallest hole the bit will be used for.
# maximum is the largest hole the bit will be used for.
#
# Each value can have a "unit of measure" added to it,
# such as 0.500mm . If you do not provide the unit of measure,
# values over 0.250 are considered millimeters, and
# values under 0.250 are considered inches. For example:
# 0.400 would be considered 0.400 mm.
# 0.125 would be considered 0.125 inches.
#
# Please note that you must use a TAB character
# between each setting on a line.
# 
# Tip: Set the TAB size of your editor to 12 characters.
#
tool	drill_size	minimum	maximum	length
T01	0.0240in	0.0000in	0.0240in	1.5in
T02	0.0620in	0.0241in	0.0999in	1.5in
T03	0.1250in	0.1000in	0.1500in	1.5in
